### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by Sacredelf** [vimeo/VimeoUpload#135]
Hello,
Could you confirm me that the API is compatible with swift 3.0 please? I saw on Github that it's ready. Do you know if it works properly? Thank you

**Comment by jasonhawkins** [comment]
Hello! On the off chance you've been holding your breath waiting for a reply since March… of 2017 (sorry about that 😬) YES VimeoUpload currently supports Swift 3.0, and we're working toward Swift 4 compatibility soon. Soonish. There's [actually a Swift 4 PR](https://github.com/vimeo/VimeoUpload/pull/181) up _right now_, but we're still working to make sure everything is in great shape before we're ready merge.

Feel free to take a look though, especially if you've upgraded your own project to Swift 4 in the last year or so (again, really really sorry 😬).
