### ISSUE TITLE
?

### ISSUE THREAD

**Issue by amajeedmuazu** [vimeo/VimeoUpload#146]

**Comment by nicolelehrer** [comment]
Hi @amajeedmuazu - thanks for reaching out. I'll get back to you with a followup as soon as I can this week.

**Comment by nicolelehrer** [comment]
Hi @amajeedmuazu - Try following the steps listed in [this document for getting started with using submodules as development pods](https://paper.dropbox.com/doc/Getting-Started-with-Submodules-as-Development-Pods-yRpNbPxIOjzGlcEbecuOC). My teammate @jasonhawkins put it together and plans on integrating this into our ReadMe's very soon. Let us know if you have any trouble - we'd love your feedback! and thanks for reaching out.

**Comment by ErAshu** [comment]
git submodule add git@github.com:vimeo/VimeoNetworking.git
Cloning into '/Users/ABC/Desktop/SampleApp/Submodules/VimeoNetworking'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
..
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by jasonhawkins** [comment]
@ErAshu Hey there! GitHub is looking for a matching public key on your machine when you try to clone  VimeoNetworking but can't find one, hence the error. 

Try following the instructions [here](https://help.github.com/articles/connecting-to-github-with-ssh/), starting with [Generating a new SSH key and adding it to the ssh-agent](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent). Then this one: [Adding a new SSH key to your GitHub account](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account).

Once you've got that set up try going through the instructions again. You should be able to successfully clone into both VimeoNetworking and VimeoUpload 🚀

**Comment by ErAshu** [comment]
@jasonhawkins  Thanks for support. Now i am able to do this. Please see the below screenshot of my project navigation. 
![screen shot 2017-08-03 at 12 22 29 pm](https://user-images.githubusercontent.com/4178384/28909577-aa5df730-7846-11e7-8178-159497cfba40.png)

I have to upload video on vimeo. I have purchased Pro account but not able to integrate vimeo uploader in my project. 
I don't know where i have to pass OAuth or client identifier in these Library? Please guide me. I stuck since 2 week. Please help me out. I have Generate OAuth from https://developer.vimeo.com/apps/[APPID]#authentication
See Screenshot
![screen shot 2017-08-03 at 12 22 46 pm](https://user-images.githubusercontent.com/4178384/28909683-17b5ad8c-7847-11e7-8e1d-5533ea280b02.png)

**Comment by ErAshu** [comment]
@jasonhawkins Please help me out.

**Comment by nicolelehrer** [comment]
@ErAshu See this section in our ReadME: 
`There's an example project for New Upload and one for Old Upload. In order to run them you'll have to drop a valid OAuth token into the example project's VimeoUpload subclass' init method where it says "YOUR_OAUTH_TOKEN". You can obtain an OAuth token by visiting developer.vimeo.com and creating a new "app" and associated OAuth token.`

**Comment by ErAshu** [comment]
I have done these in Sample Project. I am able to fetch my videos but when i going to upload, video settings file getting null. I have raised the issue but no one helping me.

You can see the issue here. https://github.com/vimeo/VimeoUpload/issues/149

**Comment by ErAshu** [comment]
@jasonhawkins  @nicolelehrer didn't here from you.

**Comment by nicolelehrer** [comment]
@ErAshu just added a response to your issue, let us know if that helps.
