### ISSUE TITLE
Swift 3.2 / 4

### ISSUE THREAD

**Issue by JakeAtArtamata** [vimeo/VimeoUpload#157]
Can you please update us on plans to support Swift 3.2 or Swift 4 so that we are able to use Vimeo on Xcode 9.

**Comment by kvaDrug** [comment]
+1. Why use Swift 3.2? It's so easy to update to 4.

**Comment by jasonhawkins** [comment]
Hello, and sorry for the lack of response on here! 

VimeoUpload currently supports Swift 3.0, and should work in any project that compiles for Xcode 9 or Xcode 10. We're currently looking to add Swift 4.0 support soon (and eventually Swift 4.2, but unfortunately that might take some more time). 

We've got [a PR open that adds compatibility with Swift 4](https://github.com/vimeo/VimeoUpload/pull/181) which might be worth checking out if you're curious. We're not ready to merge it in just yet but it's something we're hoping to take care of sooner rather than later.
