### ISSUE TITLE
Objctive c integrate issue

### ISSUE THREAD

**Issue by hirenkapoor** [vimeo/VimeoUpload#190]
i want to integrate Vimeo in my project developed in Objective C. is there any way to integrate this?

**Comment by supperspidey** [comment]
Hello @hirenkapoor ! `VimeoUpload` is a Swift library, so in order to use it in Objective-C, some modification would need to be made. There are two approaches that you can follow:

1. **If you want to use `VimeoUploader`:** Mark the class with `@objc` keyword, and remove the template (Objective-C does not support templates.) You can use `UploadDescriptor` directly instead.

2. **If you want to build something like `VimeoUploader` for your own customization:** The classes that you'll be interested in are `ReachableDescriptorManager`, `VimeoSessionManager`, and `VideoDeletionManager`. The good news is that they're all `NSObject` descendants. The logic of the umbrella class should be similar to `VimeoUploader`.

I hope that'll help you get started.

**Comment by supperspidey** [comment]
@hirenkapoor I'll close this issue for now, but if you have any question, please let us know.
