### ISSUE TITLE
Can't export Video with MOV extension on real device running iOS 13.3

### ISSUE THREAD

**Issue by Mark-Thabit** [vimeo/VimeoUpload#238]
#### Issue Summary
When trying to upload a video with mov extension to Vimeo, the export session throws this error:

`Error Domain=AVFoundationErrorDomain Code=-11838 "Operation Stopped" UserInfo={NSLocalizedFailureReason=The operation is not supported for this media., NSLocalizedDescription=Operation Stopped, NSUnderlyingError=0x10f9d60c0 {Error Domain=NSOSStatusErrorDomain Code=-16976 "(null)"}}`

#### Reproduction Steps
1. Open the camera app
2. Choose photo mode **NOT VIDEO MODE**
3. Record a QuickTake Video in **PHOTO MODE** by holding the shutter button down
4. Try to upload that video to Vimeo using **REAL DEVICE running iOS 13.3**

FYI: It's working on a simulator running iOS 13.3 and on real devices running iOS 12.4.4
and I am using Xcode 11.3 and iPhone 11 Pro Max

#### Expected Behavior
It should work fine and upload successfully

#### Actual Behavior
The exportSession fails and return an error same as in description above

**Comment by rpassis** [comment]
Hi @Mark-Thabit thanks for opening this issue.

So just to confirm, the upload work for all other video types but it fails when using quick take videos?

Please let me know and we'll look into this!

Rog

**Comment by Mark-Thabit** [comment]
Hi @rpassis 

Yes Exactly

**Comment by rpassis** [comment]
Thanks for confirming, we'll ticket this and take a look at it soon! I'll get back to you with our findings.

**Comment by rpassis** [comment]
@Mark-Thabit what version of the library are you currently using?

**Comment by Mark-Thabit** [comment]
@rpassis version 3.1.0

**Comment by Mark-Thabit** [comment]
@rpassis Any luck with the issue

**Comment by nicolelehrer** [comment]
@Mark-Thabit sorry, just for clarification, `FYI: It's working on a simulator running iOS 13.3 and on real devices running iOS 12.4.4 and I am using Xcode 11.3 and iPhone 11 Pro Max` 

^ would you mind restating which OS/device combos it is versus not working?

**Comment by Mark-Thabit** [comment]
@nicolelehrer To be clear on that

It's working on a simulator running iOS 13.3 and on real devices running iOS 12.4.4
BUT
Not working on real devices running iOS 13.1

Tools I was using during testing were Xcode 11.3 and iPhone 11 Pro Max

**Comment by nicolelehrer** [comment]
@Mark-Thabit I was able to successfully upload a video recorded in photo mode using our production app on iPhone X Pro on iOS 13.3. We use the same upload library (although we're a bit ahead, we work off of develop). It's possible either develop is working while our last release is not, or that we handle issues client side on our production app that aren't handled here. Wanted to give you a quick update in case you're able to try out develop while we look into this, but otherwise we'll try to repr using the release version you mentioned and get back to you soon.

**Comment by Mark-Thabit** [comment]
@nicolelehrer  Thanks for your feedback

**Comment by Mark-Thabit** [comment]
Issue still exists
I downloaded the latest code on develop branch and tried to upload a video made from the photo app using PHOTO MODE but with no luck, the export operation fails with the same error

![Uploading Screen Shot 2020-04-27 at 7.07.00 PM.png…]()

Video sample I used for testing

**Comment by Mark-Thabit** [comment]
Issue still exists
I downloaded the latest code on develop branch and tried to upload a video made from the photo app using PHOTO MODE but with no luck, the export operation fails with the same error

<img width="1440" alt="Screen Shot 2020-04-27 at 7 07 00 PM" src="https://user-images.githubusercontent.com/56033650/80401120-1d98be00-88bc-11ea-913f-9560ee013401.png">

Video sample I use: [here](https://github.com/Mark-Thabit/VideoSample/blob/master/IMG_0331.mov)

**Comment by nicolelehrer** [comment]
Hey @Mark-Thabit - I'll take a look and report back

**Comment by nicolelehrer** [comment]
Hi @Mark-Thabit, I can confirm I see the same issue on my device using the sample project. 

Try updating the `exportSession.outputFileType` to `AVFileType.mov` and you should have luck, let me know?

Unfortunately, we more than likely will not be updating this library with handling this use case due to some new directions we're taking client side, but we always welcome feedback and appreciate you following up on this.

**Comment by Mark-Thabit** [comment]
Hi @nicolelehrer 

Didn't get that part 
> some new directions we're taking client side

Can you explain more
