### ISSUE TITLE
Use of unresolved identifier PHAssetExportSessionOperation

### ISSUE THREAD

**Issue by DennisYA** [vimeo/VimeoUpload#243]
Guys please help with my issue.
I am trying to update Vimeo business logic with new iOS SDK 13 in my app. I did all the items from the scratch in the guide document how to integrate VimeoUpload/VimeoNetworking. But now I faced with problem that Xcode says me that PHAssetExportSessionOperation - use of unresolved identifier. I also add import lines (ViimeoUpload/ VimeoNetworking) in the file where I have a problem. However I did all the things that have been mentioned in the guide document without any warning. How can I solve this problem?

**Comment by rpassis** [comment]
Hi @DennisYA,

Because this project has been under active development, the API has changed a lot and the documentation didn't follow so the instructions there are no longer relevant.

Your best bet is to clone this repository and work off the Example projects available.

Here's a quick getting started on that:

```
$ git clone https://github.com/Vimeo/VimeoUpload.git
$ cd VimeoUpload
$ pod install
```

Open the `VimeoUpload.xcworkspace` workspace and navigate to the `NewVideoUploader.swift` file, then replace "YOUR_AUTH_TOKEN" on line 38 with your own auth token, making sure that token allows you to upload to Vimeo.

From there you should be able to build and run, and observe how the example app handles the upload. The majority of the logic that you need to consider is contained within `VideoSettingsViewController.swift`.

Once you had a chance to go over that and work on your own project, please feel free to come back here if you continue to have issues or have additional questions.

Good luck!

Rogerio

**Comment by DennisYA** [comment]
Thank you very much
