### ISSUE TITLE
AFNetworking 3

### ISSUE THREAD

**Issue by miraclebg** [vimeo/VimeoUpload#75]
Any clues how we can use VimeoUpload on a project which already uses AFNetworking - but v. 3 (the latest release)?

Thank you!

**Comment by miraclebg** [comment]
Hello?

**Comment by huebnerob** [comment]
Hi @miraclebg,

We're currently actively working on migrating this project to use AFNetworking 3.x, but we can't move it over quite yet due to conflicting dependencies in our internal projects.  

It may be possible to clone/integrate the project manually and run it off the latest AFNetworking (3.x) since we did not use any of the APIs from 2.x that were deprecated.

cc @alfiehanssen

**Comment by miraclebg** [comment]
@huebnerob Thanks for the response!

Then why don't i join in and help you on that one?

We'll need to do this anyway as soon as possible so it's better for me to help you out instead of reworking our entire codebase down to 2.x and then redo this again in a month or so.

Let me know :) We'll have to decide on something this week.

**Comment by huebnerob** [comment]
Sure, feel free to open a PR with the necessary changes if you decide to go that route, assuming the changes aren't too massive.  We can maintain an afnet-3.0 compatible branch until we stop needing 2.x compatibility.

**Comment by alfiehanssen** [comment]
Actually, in thinking about this further, we can support AF3 because we're not pulling in the entire VIMNetworking library, just the model layer, boo yah!
