### ISSUE TITLE
Could you provide VimeoUpload Objective C code or library please?

### ISSUE THREAD

**Issue by coneits** [vimeo/VimeoUpload#86]
#### Issue Summary
A brief but thorough description of the issue.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by huebnerob** [comment]
Hi @coneits, 

Although its written in Swift, this library should be fully useable from Objective-C.  Have you had any more specific issues attempting to do so?

**Comment by coneits** [comment]
could you please let me know how I can use this library on my objective c xcode project?
Currently, this library is written by swift, so should I convert this project into objective c by myselft to use this library? Thanks

**Comment by alfiehanssen** [comment]
@coneits 

Although this library is written in Swift, it can be used inside of an Objective-C project. There is no need to convert this library into Objective-C. Read the Apple docs on interoperability between Objective-C and Swift. 

VIMUpload is no longer supported. Use this library instead.

**Comment by iamabhiee** [comment]
I have added files for vimeo upload in my Objective-C project from VimeoUpload folder
I have added #import “<projectname>-Swift.h” in my project
To subclass VimeoUpload, I am adding @objc in the class definition and it gives me following error

"Generic subclasses of '@objc' classes cannot have an explicit '@objc' attribute because they are not directly visible from Objective-C.”
