### ISSUE TITLE
Unable to Reconnect to Vimeo.com After Deleting app connection on Vimeo.com

### ISSUE THREAD

**Issue by davidross2020** [vimeo/VimeoUpload#93]
I was able to connect and upload videos using the library but when I deleted the app connection on Vimeo.com (as a test) the app didn't authorize again.

the upload looks like it's working but nothing is uploaded as the app is no longer connected.

I deleted the app on the phone and restarted but it still won't re-authorize the app.

This comes up in the output: 
Vimeo upload state : Executing
Vimeo upload state : Finished
Invalid http status code for download task.

And this is in OldVimeoUpload.swift: ( didn't include the actual access code!)

import Foundation

class OldVimeoUpload: VimeoUpload<OldUploadDescriptor>
{
    static var VIMEO_ACCESS_TOKEN :String!     // = "there's a string of numbers here"
    
    static let sharedInstance = OldVimeoUpload(backgroundSessionIdentifier: "com.slatablellc.slatablevideo") { () -> String? in
        return VIMEO_ACCESS_TOKEN // See README for details on how to obtain and OAuth token
    }
    
    // MARK: - Initialization
    
    override init(backgroundSessionIdentifier: String, authTokenBlock: AuthTokenBlock)
    {
        super.init(backgroundSessionIdentifier: backgroundSessionIdentifier, authTokenBlock: authTokenBlock)
    }
}

**Comment by alfiehanssen** [comment]
Thanks @davidross2020 sounds like a legit bug, we'll take it on in an upcoming sprint. More soon.

**Comment by alfiehanssen** [comment]
Revision: This is expected behavior, I spoke too soon.

It sounds like you went to developer.vimeo.com and created an auth token. Used it to upload videos. And then went back to developer.vimeo.com and deleted the auth token. 

The app will not automatically re-authenticated in this situation. You've killed the token and the app cannot request a new one for you. You'll need to create a new auth token and plug it into the app. 

If this is not accurate and you're describing a different issue let us know. 

If you inspect the error that's thrown from the failing request I'm guessing you'll see it's a 401 unauthorized related to using an invalid token.

**Comment by davidross2020** [comment]
I'll check now and add a new auth token. As far as I am aware I deleted in my regular account but I will test with a couple of my accounts to make sure and report back.
